// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postId"`
	ParentID  *string    `json:"parentId,omitempty"`
	Content   string     `json:"content"`
	Children  []*Comment `json:"children"`
	CreatedAt string     `json:"createdAt"`
}

type CommentPage struct {
	Comments   []*Comment `json:"comments"`
	TotalCount int        `json:"totalCount"`
}

type Mutation struct {
}

type Post struct {
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Content          string     `json:"content"`
	Comments         []*Comment `json:"comments"`
	CommentsDisabled bool       `json:"commentsDisabled"`
}

type Query struct {
}

type Subscription struct {
}
